using System.Collections.Generic;

namespace Shiori.Editor
{
    /// <summary>
    /// Japanese UI strings. Plain, short sentences for people who do not know git.
    /// Simple-mode vocabulary is fixed: 保存 / 履歴 / 戻す / バリエーション / 送信 / 受信.
    /// </summary>
    internal static class JapaneseStrings
    {
        public static readonly IReadOnlyDictionary<string, string> Table = new Dictionary<string, string>
        {
            ["window.title"] = "Shiori",

            ["lock.compiling"] = "スクリプトをコンパイル中です。終わるまでお待ちください。",
            ["lock.updating"] = "Unity がアセットを更新中です。終わるまでお待ちください。",
            ["lock.playmode"] = "再生中は使えません。再生を止めてください。",
            ["lock.gitbusy"] = "処理中です。少しお待ちください。",

            ["error.git"] = "git でエラーが起きました（コード {0}）。\n{1}",
            ["error.generic"] = "エラーが起きました。\n{0}",
            ["error.settings"] = "設定ファイルを読めませんでした。\n{0}",
            ["status.checking"] = "確認中…",
            ["status.loading"] = "読み込み中…",

            ["wizard.title"] = "はじめの設定",
            ["wizard.intro"] = "このプロジェクトで履歴を使う準備をします。上から順に進めてください。",
            ["wizard.finish.message"] = "準備ができました。",
            ["wizard.finish.button"] = "完了",

            ["step.state.done"] = "完了",
            ["step.state.todo"] = "未完了",
            ["step.state.blocked"] = "先に上の手順を済ませてください",

            ["step1.title"] = "git の確認",
            ["step1.found"] = "git {0} が見つかりました。",
            ["step1.path"] = "場所: {0}",
            ["step1.notfound"] = "git が見つかりません。Shiori は git を使って履歴を保存します。\n下のボタンから git をインストールし、Unity を再起動してから「再確認」を押してください。",
            ["step1.tooold"] = "git {0} は古いため使えません（2.30 以上が必要です）。\n新しい git をインストールしてから「再確認」を押してください。",
            ["step1.lfs.found"] = "Git LFS: あり（{0}）",
            ["step1.lfs.missing"] = "Git LFS: なし（今は不要です）",
            ["step1.download"] = "ダウンロードページを開く",
            ["step1.recheck"] = "再確認",

            ["step2.title"] = "プロジェクト設定",
            ["step2.ok"] = "履歴に必要な設定になっています。",
            ["step2.explain"] = "履歴を正しく扱うために、アセットをテキスト形式で保存し、.meta ファイルを表示する設定にします。",
            ["step2.current"] = "今の設定: Asset Serialization = {0} / Version Control = {1}",
            ["step2.apply"] = "設定する",

            ["step3.title"] = "履歴に含めないもの",
            ["step3.ok"] = ".gitignore と .gitattributes に Shiori の設定が入っています。",
            ["step3.explain"] = "Library や Temp など、履歴に残す必要のないフォルダを除外する設定を .gitignore と .gitattributes に追記します。すでにある内容はそのまま残します。",
            ["step3.apply"] = "追記する",

            ["step.ext.error"] = "この手順を確認できませんでした。\n{0}",

            ["step4.title"] = "最初の保存",
            ["step4.explain"] = "プロジェクトの今の状態を、最初の履歴として保存します。",
            ["step4.done"] = "最初の保存は済んでいます。",
            ["step4.mismatch"] = "このプロジェクトは別のリポジトリ（{0}）の中にあります。この形には対応していません。",
            ["step4.identity"] = "履歴に残す名前とメールアドレスを入力してください。この PC のこのプロジェクトにだけ保存されます。",
            ["step4.name"] = "名前",
            ["step4.email"] = "メールアドレス",
            ["step4.identity.required"] = "名前とメールアドレスを両方入力してください。",
            ["step4.apply"] = "最初の保存をする",
            ["step4.progress"] = "Shiori: 最初の保存",

            ["simple.save.title"] = "保存",
            ["simple.save.message.label"] = "メモ",
            ["simple.save.button"] = "保存",
            ["simple.save.tooltip"] = "メモを書いて Enter でも保存できます。",
            ["simple.save.nochanges"] = "変更はありません",
            ["simple.save.changes"] = "{0} 件の変更（追加 {1} / 変更 {2} / 削除 {3}）",
            ["simple.save.progress"] = "Shiori: 保存",
            ["simple.meta.title"] = ".meta ファイルに問題が {0} 件あります（保存はできます）",
            ["simple.meta.missing"] = ".meta がありません: {0}",
            ["simple.meta.orphan"] = "元のファイルがありません: {0}",

            ["simple.history.title"] = "履歴",
            ["simple.history.refresh"] = "更新",
            ["simple.history.empty"] = "まだ履歴はありません。",
            ["simple.history.more"] = "もっと見る",
            ["simple.history.current"] = "現在",
            ["simple.history.files"] = "{0} 件",
            ["simple.detail.empty"] = "履歴を選ぶと、変わったファイルが表示されます。",
            ["simple.detail.nofiles"] = "変わったファイルはありません。",
            ["simple.detail.by"] = "{0:yyyy/MM/dd HH:mm} ・ {1}",
            ["row.metaonly"] = "{0}（.meta のみ）",

            ["restore.button"] = "この時点に戻す",
            ["restore.tooltip"] = "プロジェクト全体をこの時点の状態に戻します。",
            ["restore.nothing"] = "今がこの時点の状態なので、戻すものはありません。",
            ["restore.dialog.title"] = "この時点に戻す",
            ["restore.dialog.dirty"] = "現在の未保存の変更は失われます。先に保存しますか？\n\n戻す先: {0}（{1}）",
            ["restore.dialog.clean"] = "この時点に戻します。よろしいですか？\n\n戻す先: {0}（{1}）",
            ["restore.dialog.savefirst"] = "保存してから戻す",
            ["restore.dialog.discard"] = "保存せずに戻す",
            ["restore.dialog.ok"] = "戻す",
            ["restore.dialog.cancel"] = "キャンセル",
            ["restore.progress"] = "Shiori: 戻す",
            ["restore.done"] = "「{0}」の時点に戻しました。",
            ["restore.nochange"] = "すでに「{0}」の時点と同じです。",
            ["restore.stashed"] = "戻す前の変更は「取ってある変更」に残してあります。あとで取り出せます。",

            ["send.button"] = "送信",
            ["send.setup"] = "送信先を設定",
            ["send.none"] = "送信先がまだありません。保存した履歴をほかの場所にも送っておけます。",
            ["send.never"] = "まだ送信していません（保存 {0} 件）",
            ["send.unsent"] = "送信していない保存 {0} 件",
            ["send.uptodate"] = "すべて送信済みです",
            ["send.progress"] = "Shiori: 送信",
            ["send.done"] = "{0} 件の保存を送信しました。",
            ["send.nothing"] = "送信する保存はありません。",
            ["send.nothingsaved"] = "まだ保存がありません。先に保存してください。",
            ["send.unsaved"] = "保存していない変更は送信されません。送るには先に保存してください。",
            ["send.tooltip"] = "保存した履歴を送信先に送ります。保存していない変更は送られません。",

            ["receive.button"] = "受信",
            ["receive.tooltip"] = "送信先にある新しい保存を受け取り、プロジェクトを最新にします。保存していない変更があるときは受信できません。",
            ["receive.progress"] = "Shiori: 受信",
            ["receive.dialog.title"] = "受信",
            ["receive.dialog.body"] = "送信先にある新しい保存を受信して、プロジェクトを最新にします。\nこの PC の保存は消えません。",
            ["receive.dialog.ok"] = "受信",
            ["receive.done"] = "{0} 件の保存を受信しました。",
            ["receive.nothing"] = "受信する保存はありません。",
            ["receive.unsaved"] = "受信する前に、今の変更を保存してください。",
            ["receive.diverged"] = "この PC とほかの PC で別々に保存されているため、受信できません（受信を待っている保存 {0} 件）。合わせる機能は今後の版で入ります。",
            ["receive.unrelated"] = "送信先には、このプロジェクトとは別の履歴が入っています。送信先の URL を確かめてください。",
            ["receive.waiting"] = "受信できる保存 {0} 件",
            ["receive.split"] = "別々に保存されています",

            ["remote.error.Authentication"] ="送信先にサインインできませんでした。表示されたサインイン画面で、送信先のアカウントでサインインしてください。",
            ["remote.error.NotFound"] = "送信先が見つかりません。URL を確かめてください。",
            ["remote.error.Network"] = "送信先に接続できませんでした。ネットワークを確かめて、もう一度試してください。",
            ["remote.error.Rejected"] = "送信先に、この PC にない保存があるため送信できません。ほかの PC から送信していないか確かめてください。",
            ["remote.error.TooLarge"] = "大きすぎるファイルがあるため、送信先が受け付けませんでした（GitHub では 1 ファイル 100 MB まで）。",
            ["remote.error.Timeout"] = "時間内に終わりませんでした。ネットワークを確かめて、もう一度試してください。",
            ["remote.error.Unknown"] = "送信先とのやりとりに失敗しました。",

            ["remote.title"] = "送信先",
            ["remote.help"] = "GitHub などで空の非公開リポジトリを作り、その URL を貼り付けてください。非公開にしておけば、ほかの人には見えません。サインインは、初めて送信するときに表示される画面で行います。",
            ["remote.url"] = "URL",
            ["remote.check"] = "確認する",
            ["remote.apply"] = "この送信先にする",
            ["remote.checking"] = "確認中…",
            ["remote.empty"] = "空の送信先です。ここに送信できます。",
            ["remote.same"] = "このプロジェクトの保存が入っている送信先です。",
            ["remote.other"] = "この送信先には、このプロジェクトにない保存が入っています。別のプロジェクトの送信先ではないか確かめてください。",
            ["remote.saved"] = "送信先を設定しました。",
            ["remote.current"] = "今の送信先: {0}",
            ["remote.required"] = "URL を入力してください。",

            ["step.remote.title"] = "送信先（任意）",
            ["step.remote.optional"] = "任意",
            ["step.remote.explain"] = "保存した履歴を、ほかの場所にも送っておけます（バックアップ）。あとで Project Settings > Shiori からも設定できます。",
            ["step.remote.done"] = "送信先: {0}",

            ["aside.title"] ="取ってある変更（{0} 件）",
            ["aside.help"] = "「保存せずに戻す」で取っておいた変更です。取り出しても、ここからは消えません。",
            ["aside.item"] = "「{0}」に戻す前の変更",
            ["aside.item.untitled"] = "戻す前の変更",
            ["aside.button"] = "取り出す",
            ["aside.dialog.title"] = "取ってある変更を取り出す",
            ["aside.dialog.body"] = "{0}（{1}）を、今のプロジェクトに戻します。\n取ってある変更は消えずに残ります。",
            ["aside.dialog.ok"] = "取り出す",
            ["aside.dirty"] = "取り出す前に、今の変更を保存してください。",
            ["aside.overlap"] = "次のファイルは、取っておいたあとの履歴でも変わっているため、取り出せません。\n{0}",
            ["aside.more"] = "ほか {0} 件",
            ["aside.done"] = "{0} 件の変更を取り出しました。保存すると履歴に残ります。",
            ["aside.progress"] = "Shiori: 取り出す",
            ["restore.projectsettings"] = "プロジェクト設定も戻しました。反映には Unity の再起動が必要な場合があります。",

            ["settings.title"] = "Shiori",
            ["settings.git.title"] = "git の場所",
            ["settings.git.help"] = "空のままなら自動で探します。",
            ["settings.git.path"] = "git のパス",
            ["settings.git.browse"] = "参照…",
            ["settings.git.browse.title"] = "git.exe を選んでください",
            ["settings.git.auto"] = "自動で探す",
            ["settings.git.notfound"] = "git が見つかりません。",
            ["settings.mode.title"] = "表示",
            ["settings.modes.label"] = "使うモード",
            ["settings.modes.both"] = "かんたんと詳細",
            ["settings.modes.simple"] = "かんたんだけ",
            ["settings.modes.detail"] = "詳細だけ",
            ["settings.modes.help"] = "「かんたんと詳細」にすると、ウィンドウの上部で切り替えられます。",
            ["settings.user.file"] = "保存先: UserSettings/Shiori.json（この PC だけ）",
            ["settings.setup.title"] = "はじめの設定",
            ["settings.setup.completed"] = "はじめの設定は完了している",
            ["settings.setup.help"] = "チェックを外すと、次に開いたときに「はじめの設定」をもう一度表示します。",
            ["settings.ignore.title"] = "履歴に含めないもの",
            ["settings.ignore.missing"] = ".gitignore と .gitattributes に Shiori の設定がありません。",
            ["settings.ext.title"] = "追加の設定",
            ["settings.project.file"] = "保存先: ProjectSettings/Shiori.json（履歴に含まれます）",

            ["mode.label"] = "モード",
            ["mode.simple"] = "かんたん",
            ["mode.detail"] = "詳細",

            ["detail.tab.changes"] = "変更",
            ["detail.tab.history"] = "ログ",
            ["detail.tab.stashes"] = "スタッシュ",
            ["detail.commit.label"] = "メッセージ",
            ["detail.commit"] = "コミット",
            ["detail.commit.tooltip"] = "すべての変更をステージしてコミットします（git add -A と git commit）。メッセージが空なら自動で付けます。",
            ["detail.commit.progress"] = "Shiori: コミット",
            ["detail.commit.done"] = "コミットしました: {0}",
            ["detail.commit.nothing"] = "コミットする変更はありません。",
            ["detail.push"] = "プッシュ",
            ["detail.push.tooltip"] = "現在のブランチを origin にプッシュします。強制プッシュはしません。",
            ["detail.pull"] = "プル",
            ["detail.pull.tooltip"] = "origin から fetch して fast-forward します。マージやリベースはしません。作業ツリーに変更があるときはできません。",
            ["detail.remote.setup"] = "リモートを設定",
            ["detail.remote.none"] = "リモート（origin）がありません",
            ["detail.remote.status"] = "origin: ↑{0} ↓{1}",
            ["detail.remote.diverged"] = "origin: ↑{0} ↓{1}（分岐しています）",
            ["detail.remote.unknown"] = "origin: まだ fetch していません",
            ["detail.push.done"] = "{0} 件のコミットをプッシュしました。",
            ["detail.push.nothing"] = "プッシュするコミットはありません。",
            ["detail.pull.done"] = "{0} 件のコミットを取り込みました（fast-forward）。",
            ["detail.pull.nothing"] = "取り込むコミットはありません。",
            ["detail.pull.dirty"] = "作業ツリーに変更があるため、プルできません。先にコミットしてください。",
            ["detail.pull.diverged"] = "ローカルと origin が分岐しているため、fast-forward できません（origin 側に {0} 件）。マージは今後の版で入ります。",
            ["detail.pull.unrelated"] = "origin には、このリポジトリと共通の履歴がありません。リモートの URL を確かめてください。",
            ["detail.log.empty"] = "コミットはまだありません。",
            ["detail.log.more"] = "さらに読み込む",
            ["detail.log.select"] = "コミットを選ぶと、変更されたファイルが表示されます。",
            ["detail.log.restore"] = "この状態に戻す",
            ["detail.log.restore.tooltip"] = "作業ツリーをこのコミットの状態にして、新しいコミットとして記録します（かんたんモードの「戻す」と同じです）。",
            ["detail.log.meta"] = "{0}  {1:yyyy/MM/dd HH:mm}  {2}",
            ["detail.stash.help"] = "git stash のエントリです。適用しても消えません。作業ツリーがきれいで、スタッシュ後に同じファイルが変わっていないときだけ適用します。",
            ["detail.stash.empty"] = "スタッシュはありません。",
            ["detail.stash.apply"] = "適用",
            ["detail.stash.dialog.title"] = "スタッシュを適用",
            ["detail.stash.dialog.body"] = "{0}\n{1}\nを作業ツリーに適用します。スタッシュは残ります。",
            ["detail.stash.progress"] = "Shiori: スタッシュを適用",
            ["detail.stash.done"] = "スタッシュを適用しました（{0} ファイル）。",
            ["detail.stash.dirty"] = "作業ツリーに変更があるため適用できません。先にコミットしてください。",
            ["detail.stash.overlap"] = "スタッシュのあとで次のファイルも変わっているため、適用できません。\n{0}",
            ["detail.head"] = "HEAD",
            ["detail.unity.view"] = "Unity 表示",
            ["detail.unity.text"] = "テキスト",
            ["detail.unity.view.tooltip"] = "GameObject・コンポーネント・プロパティごとに、何が変わったかを表示します。",
            ["detail.unity.added"] = "追加",
            ["detail.unity.removed"] = "削除",
            ["detail.unity.changed"] = "変更",
            ["detail.unity.none"] = "Unity から見た変更はありません（並び順や書式だけの違いです）。",
            ["detail.unity.loading"] = "読み込み中…",

            ["detail.files.title"] = "変更ファイル",
            ["detail.files.empty"] = "変更はありません",
            ["detail.refresh"] = "更新",
            ["detail.diff.select"] = "ファイルを選ぶと差分が表示されます。",
            ["detail.diff.none"] = "表示できる差分はありません。",
            ["detail.diff.truncated"] = "長いので先頭 {0} 行だけ表示しています。",

            ["time.now"] = "たった今",
            ["time.minutes"] = "{0} 分前",
            ["time.hours"] = "{0} 時間前",
            ["time.days"] = "{0} 日前",
            ["time.date"] = "{0:yyyy/MM/dd}",

            ["kind.added"] = "追加",
            ["kind.modified"] = "変更",
            ["kind.deleted"] = "削除",
            ["kind.renamed"] = "名前の変更",
            ["kind.copied"] = "コピー",
            ["kind.typechanged"] = "種類の変更",
            ["kind.unmerged"] = "競合",
            ["kind.ignored"] = "無視",
            ["kind.unknown"] = "不明",
        };
    }
}
